### ISSUE TITLE
Copyright claim for 'multipart' developers

### ISSUE THREAD

**Issue by alexanderkjall** [cybergeek94/const-cstr#4]
Hi

The LICENSE-MIT file says that copyright is owned by `The multipart Crate Developers` here: https://github.com/abonander/const-cstr/blob/master/LICENSE-MIT#L1

But Cargo.toml says that the author is `Austin Bonander <austin.bonander@gmail.com>`.

I presume that this is a copy-paste error? Would be great to get clarification on this in order for me to be able to package the crate for debian.

best regards

**Comment by abonander** [comment]
Fixed, it was a copypaste error.

For the record, I am the principal developer of both crates but they have received minor contributions.
